global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "execution-server"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["execution:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
