import { Link } from "wouter";
import { motion } from "framer-motion";
import { Shield, ArrowLeft, AlertTriangle } from "lucide-react";

const RISK_SECTIONS = [
  {
    heading: "1. Trading Risk",
    body: "Trading perpetual futures, cryptocurrencies, and other financial instruments involves substantial risk of loss. You may lose some or all of the capital you allocate to trading. Past performance of any algorithm, signal, or strategy is not indicative of future results. Never trade with money you cannot afford to lose.",
  },
  {
    heading: "2. Leverage Risk",
    body: "Leverage amplifies both gains and losses. A small adverse price movement can result in the total loss of your position. You are responsible for understanding how leverage affects your portfolio and for setting position sizes appropriate to your risk tolerance.",
  },
  {
    heading: "3. Automated Trading Risk",
    body: "Anavitrade provides automated trade signals and optional automated execution. Automated trading systems can fail, produce unexpected results, or execute trades under market conditions that differ from those anticipated at the time the signal was generated. You should monitor automated trading activity regularly and be prepared to intervene at any time.",
  },
  {
    heading: "4. Simulated Performance",
    body: "Any performance figures, returns, win rates, or other metrics displayed on the Anavitrade website or platform are based on simulated or hypothetical trading using historical data unless explicitly labeled as live-traded results. Simulated performance has inherent limitations: it does not represent actual trading, does not account for slippage, liquidity constraints, or execution delays, and may overstate or understate the results achievable in live markets. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown.",
  },
  {
    heading: "5. Technical Risk",
    body: "Anavitrade relies on third-party infrastructure including cloud providers, blockchain networks, exchange APIs, and wallet connectivity services. System failures, network congestion, API rate limits, maintenance windows, or cyber attacks may delay or prevent signal delivery or trade execution. You acknowledge that Anavitrade is not responsible for losses arising from such technical failures.",
  },
  {
    heading: "6. Exchange and Counterparty Risk",
    body: "When you connect an exchange API key or trade through a DEX, your counterparty risk includes the solvency, security, and operational integrity of that exchange or protocol. Anavitrade does not control and is not responsible for the actions or failures of third-party exchanges, liquidity providers, or blockchain networks.",
  },
  {
    heading: "7. No Guarantee of Profitability",
    body: "Anavitrade makes no guarantees, express or implied, regarding the profitability of its signals or strategies. Trading algorithms and quantitative models are based on historical patterns and statistical probabilities, which may not persist in future market conditions. Past backtest results, win rates, and Sharpe ratios are not guarantees of future performance.",
  },
  {
    heading: "8. Jurisdictional Restrictions",
    body: "The availability of Anavitrade's services may be restricted in certain jurisdictions. It is your responsibility to ensure that your use of the platform complies with applicable laws and regulations in your country of residence. Anavitrade reserves the right to restrict access from jurisdictions where its activities may be regulated without an appropriate license.",
  },
  {
    heading: "9. No Personal Advice",
    body: "Anavitrade does not provide personalized investment advice, financial planning, legal advice, or tax advice. All signals and strategies are generated by automated algorithms based on quantitative models. You should consult with qualified financial, legal, and tax professionals before engaging in trading activity.",
  },
  {
    heading: "10. API Key Risk",
    body: "When you provide exchange API keys, you are granting Anavitrade permission to submit orders on your behalf within the permissions you configure. You are responsible for setting appropriate API key permissions (trade-only, withdrawals disabled) and for revoking keys if you no longer wish to use the service. Anavitrade uses industry-standard encryption for stored credentials but cannot guarantee that stored keys are invulnerable to all security threats.",
  },
];

export default function RiskDisclosure() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border/50 px-6 py-4 sticky top-0 z-40 bg-background/80 backdrop-blur-xl">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/">
            <div className="flex items-center gap-3 cursor-pointer group">
              <div className="w-8 h-8 rounded-xl bg-primary flex items-center justify-center font-bold text-primary-foreground text-sm group-hover:scale-105 transition-transform">@</div>
              <span className="font-heading font-bold text-foreground hidden sm:block">Anavitrade</span>
            </div>
          </Link>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Shield className="w-3.5 h-3.5 text-primary" />
            Risk Disclosure
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: [0.23, 1, 0.32, 1] }}
        >
          {/* Back link */}
          <Link href="/">
            <div className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8 cursor-pointer group">
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
              Back to home
            </div>
          </Link>

          {/* Title */}
          <div className="mb-10">
            <h1 className="text-4xl font-heading font-bold text-foreground mb-3">Risk Disclosure</h1>
            <p className="text-muted-foreground text-sm">Last updated: July 2026</p>
          </div>

          {/* Warning banner */}
          <div className="p-5 rounded-2xl mb-10" style={{ background: "oklch(0.60 0.22 50 / 0.06)", border: "1px solid oklch(0.60 0.22 50 / 0.20)" }}>
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-muted-foreground leading-relaxed">
                <strong className="text-foreground">Trading carries significant risk.</strong> Please read this entire document carefully before using the Anavitrade platform. This disclosure is provided for informational purposes and does not constitute legal or financial advice.
              </p>
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-8">
            {RISK_SECTIONS.map((section, i) => (
              <motion.div
                key={section.heading}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05, duration: 0.4, ease: [0.23, 1, 0.32, 1] }}
                className="pb-8 border-b border-border/30 last:border-0"
              >
                <h2 className="text-base font-semibold text-foreground mb-3">{section.heading}</h2>
                <p className="text-muted-foreground text-sm leading-relaxed">{section.body}</p>
              </motion.div>
            ))}
          </div>

          {/* Footer nav */}
          <div className="mt-12 pt-8 border-t border-border/30 flex items-center justify-between flex-wrap gap-4">
            <p className="text-xs text-muted-foreground">
              Questions? Contact us at{" "}
              <a href="mailto:legal@anavitrade.com" className="text-primary hover:underline">legal@anavitrade.com</a>
            </p>
            <div className="flex items-center gap-4 text-xs">
              <Link href="/terms" className="text-muted-foreground hover:text-foreground transition-colors">Terms of Service</Link>
              <Link href="/privacy" className="text-muted-foreground hover:text-foreground transition-colors">Privacy Policy</Link>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
